eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service  # يجب أن يتطابق مع الاسم في gateway/config-server
          uri: http://localhost:8050
          predicates:
            - Path=/api/users/**
        - id: course-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/courses/**
        - id: course-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/enrollments/**


